### ISSUE TITLE
难道你真的是天才？！

### ISSUE THREAD

**Issue by xiaohuangbo** [apernet/OpenGFW#1]
老实说，我就知道会有这样离谱的项目出现，先点个star看看这个项目的后续发展如何，感觉潜力很大啊！😝

**Comment by analytic-bias** [comment]
![image](https://github.com/apernet/OpenGFW/assets/6694864/b33151de-da34-41a1-ac12-f5ccee190617)

**Comment by sdfsdfsdf145314364** [comment]
就他妈离谱这脑子，做这玩意。

**Comment by Argon4W** [comment]
太逆天了，star了

**Comment by 64xi** [comment]
> ![image](https://private-user-images.githubusercontent.com/6694864/298289570-b33151de-da34-41a1-ac12-f5ccee190617.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Njg0NDgsIm5iZiI6MTcwNTc2ODE0OCwicGF0aCI6Ii82Njk0ODY0LzI5ODI4OTU3MC1iMzMxNTFkZS1kYTM0LTQxYTEtYWMxMi1mNWNjZWUxOTA2MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMTYyOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2MzAyOGFiN2FiNjNiMzkwMWI2OTJjYWZjNTU3YjNhZGFhNmJjNGE0ZWJjYjBjYzljYjU1MWIxNzhhMThlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.30hA0btJyf5X_KX82vTlqM329h11jIbNkdPFU3347SY)

習皇陛下　万歳
