### ISSUE TITLE
Can anyone identify the author?

### ISSUE THREAD

**Issue by siutung** [apernet/OpenGFW#104]
Can anyone identify the author?

Shouldn't he be an official Chinese person?

By the time you install and deploy and use it, the Chinese police will be able to make precise arrests.:-)

**Comment by tobyxdd** [comment]
Why would you be arrested for deploying your own GFW? Chairman Xi would be proud of you

![image](https://github.com/apernet/OpenGFW/assets/1414953/485dfa18-ffbe-4c74-96d5-704389eccee7)
