### ISSUE TITLE
Delete OpenGFW. 

### ISSUE THREAD

**Issue by YisuiDenghua** [apernet/OpenGFW#12]
I am worried that the Chinese government will learn from this project and strengthen GFW, thereby causing losses to Chinese software developers. Such as not being able to access their projects or being unable to contact the company where they work remotely.

**Comment by Rabbit0w0** [comment]
Don't worry about it.

**Comment by UjuiUjuMandan** [comment]
You can pretend to be any government-related entity and send takedown notice to GitHub. They will definitely suspended this to Chinese IPs.

**Comment by justin-himself** [comment]
> I am worried that the Chinese government will learn from this project and strengthen GFW, thereby causing losses to Chinese software developers. Such as not being able to access their projects or being unable to contact the company where they work remotely.

Then submit an issue on Chinese government website, not here
