### ISSUE TITLE
你们搞的这个东西啊，excited！

### ISSUE THREAD

**Issue by xijinping0** [apernet/OpenGFW#2]
把 GFW 推向全世界全宇宙！

![](https://pbs.twimg.com/media/FfU3XLIVUAA_el2?format=jpg&name=small)

https://lovers.xijinping.one

**Comment by jzhong0821** [comment]
支持了

**Comment by Smallthing** [comment]
你发的这个图其实很脑残。

**Comment by yulon** [comment]
这项目是什么奇怪的名字啦，时间线上看到有人 star 了两眼一黑。
另外建议开个 Discussions，就不用让吐槽污染 Issues 了。

**Comment by f1098** [comment]
有这功夫，整点别的不好。

**Comment by justin-himself** [comment]
> 你发的这个图其实很脑残。

你其实很聪明 👍

**Comment by meritamen** [comment]
> 有这功夫，整点别的不好。

有这功夫还是要多写点屎山，多养几只小奴隶，多做几次核酸

**Comment by ImAlexBlock** [comment]
坏事做尽（恼）

**Comment by ccpfucker** [comment]
加速⏩
