### ISSUE TITLE
[建议] 增加dns挟持功能，自由定制爱国主义弹窗

### ISSUE THREAD

**Issue by funnychip796** [apernet/OpenGFW#21]
https://www.zhihu.com/question/20418863

**Comment by tobyxdd** [comment]
Not possible with HTTPS

**Comment by SleepyBag** [comment]
This is actually possible because in some networks the admins are able to force users to install admin's self-signed root certificates. Please consider reopen this. This can be done with a configurable man-in-the-middle certificate and a list of to be attacked-in-the-middle host list.

**Comment by KaraRyougi** [comment]
> This is actually possible because in some networks the admins are able to force users to install admin's self-signed root certificates.

Installing 3rd party root certs on iOS, macOS, and Windows devices is possible. However, my understanding is that Android does not support it.

It would be a useful feature though. Many commercial "NGFW" firewalls are just that - firewalls with TLS MITM capabilities.
