### ISSUE TITLE
Couldn't load match `connmark':No such file or directory (WSL)

### ISSUE THREAD

**Issue by mar-heaven** [apernet/OpenGFW#24]
failed to parse config  {"error": "invalid config: io: running [/usr/sbin/iptables -t filter -C INPUT -m connmark --mark 1001 -j ACCEPT --wait]: exit status 2: iptables v1.8.7 (nf_tables): Couldn't load match `connmark':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information

**Comment by mar-heaven** [comment]
@tobyxdd It's already under root

**Comment by tobyxdd** [comment]
What device and kernel version are you running?

**Comment by mar-heaven** [comment]
ThinkBook14 G5+ APO 
CPU: AMD Ryzen 7 7840H with Radeon 780M Graphics
uname -a
Linux Ginta 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tobyxdd** [comment]
Oh, this project does not support WSL unfortunately, as its kernel is stripped down by Microsoft and lacks a lot of networking features

**Comment by mar-heaven** [comment]
I got it, will Windows be supported in the future?

**Comment by zhufengning** [comment]
wsl可通过自己编译内核开启相关功能。不过我的报错跟你的不一样，不知道行不行。参考：<https://github.com/microsoft/WSL/issues/6044#issuecomment-1197337831>
