### ISSUE TITLE
工作原理？

### ISSUE THREAD

**Issue by huyuguang** [apernet/OpenGFW#5]
这个东西的工作原理是什么？GFW应该是通过端口镜像获得ip包，是并联的吧？这个东西是不是得网关串联接入？

**Comment by tobyxdd** [comment]
目前是基于 netfilter queue (nfqueue) 的, https://netfilter.org/projects/libnetfilter_queue/doxygen/html/

**Comment by Tension-Z** [comment]
如果实现并联检测会进一步完善这个项目
