### ISSUE TITLE
感觉有个代码相关的bug

### ISSUE THREAD

**Issue by PICKQUE** [apernet/OpenGFW#51]
ssh.go 里面关于 Feed 函数里面, 两个分支都是先把update置为false,但是后面更新propupdate变量需要update变量为true的情况下,所以说永远都更新不了 propupdate 变量. 
<img width="628" alt="image" src="https://github.com/apernet/OpenGFW/assets/38390188/4a9e2491-7613-4a24-8df8-abc40e55aa82">
我的理解应该是这样的
<img width="570" alt="image" src="https://github.com/apernet/OpenGFW/assets/38390188/9a7f9b01-89bd-4264-aa60-e2a500663fec">

当然也可能是我对代码的理解有误

**Comment by tobyxdd** [comment]
你理解错了，`s.serverLSM.Run()` 和 `s.clientLSM.Run()` 会执行下面的 `s.parseClientExchangeLine` / `s.parseServerExchangeLine`，里面会改变这两个变量

**Comment by PICKQUE** [comment]
哦哦 理解了 谢谢
