### ISSUE TITLE
Panic is triggered by none dns packet (?)

### ISSUE THREAD

**Issue by taida957789** [apernet/OpenGFW#60]
![image](https://github.com/apernet/OpenGFW/assets/3710930/24afde24-2a3f-4c26-9978-882ea4b94628)

**Comment by taida957789** [comment]
It seems to be a problem with gopacket processing dns packets. You may use recover to solve the panic when processing these packets.

there is no any buffer size checking at DNSQuestion.decode function
![image](https://github.com/apernet/OpenGFW/assets/3710930/e61f2e91-75a7-4fb7-85c8-863f1d56bdc1)

**Comment by tobyxdd** [comment]
Oops, I had no idea that gopacket would just panic on invalid packets like that. Perhaps the best solution would be to fix `DNSQuestion.decode` and submit a PR to them?

**Comment by taida957789** [comment]
Yes, I think so, but from the point of view of using the library, do we need to consider adding a fault-tolerance mechanism to the analyzer?

**Comment by tobyxdd** [comment]
Turns out the latest version of gopacket already has this fix. I will just upgrade to the new version for now.
