### ISSUE TITLE
有没有实际测试和真正的GFW相比，哪个更强

### ISSUE THREAD

**Issue by 14790897** [apernet/OpenGFW#7]

**Comment by rammiah** [comment]
如果能识别reality就比gfw强了

**Comment by novohool** [comment]
> 如果能识别reality就比gfw强了

它不是不能，是投入和影响

**Comment by rammiah** [comment]
> > 如果能识别reality就比gfw强了
> 
> 它不是不能，是投入和影响

ip白名单，我上我也行

**Comment by meishiffx** [comment]
> > > 如果能识别reality就比gfw强了
> > 
> > 
> > 它不是不能，是投入和影响
> 
> ip白名单，我上我也行

也不能全墙了吧（
不过大部分人看不到其实好点。见过有些完全洗脑的，还有有必要的。
中国人太相信媒体了
