### ISSUE TITLE
能屏蔽openvpn吗

### ISSUE THREAD

**Issue by do02fw** [apernet/OpenGFW#90]
能屏蔽openvpn吗

**Comment by tobyxdd** [comment]
暂时不能，不过确实有计划

**Comment by do02fw** [comment]
我目前一直用的最新版openvpn tls1.3 udp协议来翻，不知道能不能识别，反正速度挺快，也没封IP

**Comment by do02fw** [comment]
最新版是2.6.9，我是手动添加了官方的存储库，用的这个脚本安装的，https://github.com/Nyr/openvpn-install，如果你们成功识别了openvpn，我就立马换协议
