### ISSUE TITLE
Openwrt lean x86_64 运行提示缺少文件，但不知道缺少什么。

### ISSUE THREAD

**Issue by nw3000** [apernet/OpenGFW#94]
root@router:/tmp# ./OpenGFW -c config.yaml rules.yaml
bash: ./OpenGFW: cannot execute: required file not found

root@router:/tmp# opkg list | grep kmod-ipt-nfqueue
kmod-ipt-nfqueue - 6.1.81-1
root@router:/tmp# opkg list | grep iptables-mod-nfqueue
iptables-mod-nfqueue - 1.8.7-2
root@router:/tmp# opkg list | grep kmod-nf-conntrack-netlink
kmod-nf-conntrack-netlink - 6.1.81-1

**Comment by tobyxdd** [comment]
这种一般是 libc 对不上导致的，用 `CGO_ENABLED=0` 编译纯静态版本试试呢

**Comment by keekychen** [comment]
> 这种一般是 libc 对不上导致的，用 `CGO_ENABLED=0` 编译纯静态版本试试呢

 `CGO_ENABLED=0 go build` 确认可行，谢谢！

**Comment by nw3000** [comment]
> 这种一般是 libc 对不上导致的，用 `CGO_ENABLED=0` 编译纯静态版本试试呢

CGO_ENABLED=0 go build 
确认可行，谢谢！
